### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by changyujiang** [changyujiang/Mark-down#18]
- [ ] Learn JMeter 

- [ ] Learn Java EE
  - [x] Servlet 1 (get request, send response, chinese char encoding, lifecycle)
  - [x] Servlet 2 (redirect server/client; servlet auto-start/ uploadFile)
  - [ ] Servlet 3 
- [ ] Learn React/Redux
